language: php

php:
  - 5.4

notifications:
  email:
    - woxxy@foolrulez.org

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - cd tests

script: phpunit --configuration phpunit.xml --coverage-text